### ISSUE TITLE
Remember corrected tags [feature request]

### ISSUE THREAD

**Issue by harsgak** [kawaiiDango/pScrobbler#12]
When scrobbling a track with unparseable track info we can edit scrobble live. In other cases we can correct it after the scrobble. It would be useful and convenient if pscrobbler could remember these corrections instead of having to manually do them after every play of that track.

As a reference [Webscrobbler](https://github.com/web-scrobbler/web-scrobbler) is a browser based scrobbler that does implement this feature.
I think a simple dictionary storing mappings from the raw title info to the users edited scrobble info would do the trick. If the played track exists in the "edits" dictionary use that mapping else use regular parsing.

This feature would also resolve #11

**Comment by JohnGeorgine** [comment]
Just joining the thread to say I actually asked for a very similar feature in an email I sent to the developer a few days ago. My goal was to overcome the problem I and many others face on streaming apps where some tracks are provided with unnecessary info in the title, like "(Album Version)", "(Remastered)", etc. I even mentioned some kind of list/dictionary/map to store user-created patterns as well, but never got a response. Now I think I know why. It's unfortunate the developer finds it "a mess" and most likely won't be doing it, but I hope it's reconsidered some time in the future as it would really, really help me.

**Comment by harsgak** [comment]
@JohnGeorgine While I understand your frustration you must understand that implementing such a feature might not be as straightforward as it seems. With an app like this one supporting so many varied sources trying to code in this feature hastily could indeed turn out to be a mess (code wise). Probably will also lead to some headaches maintaining it.

The repo owner might be reluctant to go down that rabbit hole just yet. 

Still you don't have to wait. The app has been made open source. So anyone like you or me could fork this project, try to integrate the feature and then push it upstream while the owner focuses on the core app. Let me know if you want to give it a go.

**Comment by harsgak** [comment]
@JohnGeorgine @kawaiiDango  Could you please clarify what you meant by "user created patterns"?  I don't quite understand.

Also in my experience the app does already strip off info with brackets like  "(Remastered)". I believe its implemented [here](https://github.com/kawaiiDango/pScrobbler/blob/master/app/src/main/java/com/arn/scrobble/Stuff.kt). @JohnGeorgine Maybe you've found a bug. Or is it a resolved issue?

**Comment by kawaiiDango** [comment]
Could be regex patterns or simple wildcard patterns. 

@harsgak That code is only used for youtube and chrome, for parsing titles into artist - track

**Comment by harsgak** [comment]
@kawaiiDango Oh! Thanks. I didn't know it was only for Youtube and Chrome. 
Could you possibly add some documentation regarding the structure of the code and information flow etc so that its easier to hack.  I am sorry if its already there somewhere or obvious, I am not familiar with Kotlin/Android .

**Comment by JohnGeorgine** [comment]
First of all, I'm sorry if I sounded pretentious, like if I was demanding too much from the developer. I appreciate what's been done so far and Pano Scrobbler has easily become my favorite scrobbler. Sure, I could try and make my own version of what I'm asking, but the fact is: I sincerely thought this was a simple thing to do, at least more simple than having to deal with the varied music sources.
While I admit I haven't stopped to study the code in detail, I actually didn't think the sources would influence what I suggested at all, as I imagined the app could grab the song info from them like it already does and simply change it according to the user-defined patterns, all before sending it to Last.fm (or Libre.fm, etc).

Right now, what I imagine the app does, very roughly speaking, is:

> Grabs song info from media players
> ↓
> Sends it to scrobbling servers (Last.fm, Libre.fm, etc)

With my suggestion, I had imagined it could be as simple as adding an extra, middle step to the process, like:

> Grabs song info from media players
> ↓
> Changes info based on user-created patterns (locally, before anything is sent anywhere)
> ↓
> Sends it to scrobbling servers (Last.fm, Libre.fm, etc)

Of course, this is all just a really long shot and I could very well be completely wrong about all of this. But if there's any truth in it, I can't see how the media players (Spotify, Google Play Music, YouTube, etc) could influence the information being changed at all, not after it's already been collected and is just sitting there waiting to be sent to the server(s).

Now regarding the patterns, I'm sorry if I wasn't clear enough, but I think kawaiiDango already explained well what I meant. Regex would definitely do it, but if it's too complicated for the common user, simple wildcards would be okay as well. I vote, though, for manually, user created patterns, because of situations like that:

![example 1](https://user-images.githubusercontent.com/37919320/46629978-1b73e080-cb19-11e8-97d8-033527936b8d.png)

The first two tracks (from an hour ago) are exactly the same, but because of different tags included by different streaming services, duplicate entries end up being created on Last.fm. It could very well be handled automatically by Pano Scrobbler, but when it comes to the last two track (2 hours ago)... I don't even know how the app could handle those. They have, at the same time:
1. Real and authentic information ("The Death Of Art" in the third one);
2. Unnecessary information ("Album Version", "Explicit", "Outro");
3. A typo, like when two parentheses are opened but only one is closed in the fourth one.

A user could specifically target the last track, for example, and create a pattern like (asterisk being used as a wildcard):
> \* **(Album Version (Explicit)**

Or, inversely:

>**Marilyn Manson — The Golden Age Of Grotesque***

...Telling Pano Scrobbler what to hide and what to keep.

If the user, for some reason, wanted to keep the "Album Version" and "Outro" parts and just hide the "Explicit" part of the third track, it could (theoretically) be as simple as:

>**Marilyn Manson — Obsequey (The Death Of Art) (Album Version** ***- Outro)**

It could even handle situations like the ones below:

![image](https://user-images.githubusercontent.com/37919320/46631593-41e84a80-cb1e-11e8-9f3b-dfe481edeaf0.png)

While tracks 1 and 2 are simply duplicates of the same track, tracks 3 and 4 are indeed legitimate, different tracks. Again, a user concerned with that (and I'm definitely the kind of user who gets concerned with that, lol) could target the second song specifically, with a pattern like:

>**Poppy — Time Is Up***

----------------

I'm sorry if it ended up being too long. I just didn't want to create any misunderstanding like I did previously. I appreciate whoever has read so far. Thank you.

**Comment by harsgak** [comment]
> 
> This does not resolve #11 as some players put wrong metadata as the artist/track. Some casting apps put the cast device name as the artist.

I understand now. This wont actually resolve #11 but could act as band-aid for such a cases if you use such apps infrequently.

**Comment by kawaiiDango** [comment]
edits will now be remembered
