### ISSUE TITLE
Seems scrobbling from Sonos on Android just stopped working

### ISSUE THREAD

**Issue by pauly** [kawaiiDango/pScrobbler#133]
I've used this happily for a while, but something just changed and now my Sonos app on Android is not scrobbling. Other apps on the phone still are (Player FM podcast for example), and Sonos app is still showing notifications. Sonos app is still on the list to be scrobbled from, and "auto detect new music-like apps" is still checked.
Sonos app version is 13.0.5
Pano version is 2.10 - 30.Apr.21

**Comment by kawaiiDango** [comment]
I'd need logs. Send a bug report from the app after reproducing this issue

**Comment by kawaiiDango** [comment]
According to the logs, it looks like the scrobbling service was not running until a few minutes ago. Check dontkillmyapp.com Also, it didn't record any media events from sonos. Probably because the scrobbler was not running, or sonos no longer sends media events, or you didn't play anything on sonos in those few minutes.

**Comment by pauly** [comment]
strange, it seems to be starting up automatically when I use PlayerFM but
in the last few days it is not starting up automatically when I use Sonos.
I can't be exactly sure when it stopped. Thanks for looking anyway.
