### ISSUE TITLE
Add fastlane to Crowdin

### ISSUE THREAD

**Issue by sakci** [kawaiiDango/pScrobbler#192]
I think the store page should be localized as well.

**Comment by comradekingu** [comment]
@sakci Since very few people use Crowdin, and I can't contribute there, how about using Weblate.
That should bring the numbers up.

**Comment by sakci** [comment]
> @sakci Since not a lot of people use the closed source Crowdin, how about using the libre software Weblate.

I mean, the only reason I mentioned Crowdin is because Pano Scrobbler is already using it to localize in-app strings. So I really don't really understand why you brought Weblate into conversation out of the blue.

**Comment by comradekingu** [comment]
Yes, it begs the question of whether people do use Crowdin to localize Pano Scrobbler.
With 5 languages have coverage in 6 months, that isn't really the case.
For someone to translate fastlane files, results are likely to drop off from there.
It makes all the sense in the world for a libre software app to use a libre software tool.
There is just that one viable tool in Weblate atm, so that is why I suggested it.
I think the store page should be localized aswell, and I think it could be with the better tool.

**Comment by sakci** [comment]
Ah, I understand. Thank you for elaborating.

Although, I am not sure whether switching to another TMS would help. While I wholeheartedly support the use of Libre software, and I realize that alone is a good reason to use Weblate, I don't think it'd bring more translators.

Example:
* Workout'N'Rest, a Weblate project I contributed: https://hosted.weblate.org/projects/httpsgithubcomsenplfit-workout-fast/#languages
* Loop Habit Tracker, a Crowdin project I contributed: https://translate.loophabits.org/

I am not trying to discourage anyone from using Weblate though. Indeed, it's a great TMS.

**Comment by kawaiiDango** [comment]
The store's long description changes as new features are added.
Translations may not catch up. Also, I think that the description is long
and unorganised. It is just a dump of features that were added, in
chronological order. It will need a rewrite.

Btw, pano scrobbler isn't completely libre. It uses many closed source
libraries.
