### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [kawaiiDango/pScrobbler#2]
Hi,

Since your app is GNU GPL v3 licensied, is it possible to have it on [F-Droid](https://f-droid.org/) ? It's an installable catalogue of only FOSS applications.
You can find some documentation [here](https://f-droid.org/docs/). I can help you with the [Request For Packaging](https://gitlab.com/fdroid/rfp).

Just a question : are all your dependencies listed in the gradle free and open-source too ?

By the way, thanks for this app :+1: :smiley:

**Comment by kawaiiDango** [comment]
Yes, all of my dependencies are open source, but I heard that fdroid builds apks from source only and I'm not sure if publishing the API keys in the source is a good idea.

**Comment by Poussinou** [comment]
Hum yes that's right [F-Droid doesn't get API keys itself](https://f-droid.org/fr/docs/FAQ_-_App_Developers/#can-apks-signed-by-my-key-be-included). I don't know what to think about this...

@relan what about this subject of APIs, I'm still new to F-Droid, sorry for the inconvenience...

**Comment by relan** [comment]
F-Droid requires API keys to be available either in app source code or F-Droid build recipie (which is also public). That's because if some part of an app is not available (kept secrect), this app is non-free.

There are apps on F-Droid that don't bother to hide API keys and I've never heard of any problems they had with this.

**Comment by Rudloff** [comment]
Another solution is to ask for an API key the first time the user opens the app.

**Comment by GreatBigWhiteWorld** [comment]
Any plan to support FDroid?

**Comment by kawaiiDango** [comment]
No

**Comment by Poussinou** [comment]
We currently can't include this app in F-Droid ( see this [link](https://gitlab.com/fdroid/rfp/issues/610)), so I'm closing this issue.

**Comment by Efreak** [comment]
I'll add this to my own repo at animanga.efreakbnc.net/Fdroid/repo. It doesn't really fit with the other apps there, but it'll allow automatic updates with Fdroid privileged extension. If @IzzySoft wants to host it, that would be better, as I'm trying to keep my repos small.

**Comment by kawaiiDango** [comment]
As of 2022, the app now uses non free dependencies such as Google Play billing, Crashlytics and Acrcloud.

**Comment by Soundtoxin** [comment]
Can you tell us which release was the last without non-free dependencies, please?

**Comment by kawaiiDango** [comment]
207 (2.7 - 16.Apr.21)

**Comment by Soundtoxin** [comment]
I only see the latest release. Do the old ones get deleted..?

**Comment by kawaiiDango** [comment]
I haven't been using GitHub releases until yesterday

**Comment by Kladki** [comment]
Since it's mentioned on the 4.0 release notes that "The builds provided on Github no longer contain non-free dependencies", could having pano on F-Droid be a possibility now?

**Comment by Kladki** [comment]
I personally just use Listenbrainz, so that doesn't really effect me. You could maybe have a warning with those two scrobblers saying that the non-F-Droid variants have their own API keys built in, suggesting you use eithe the Github or Google play variants if you want to use those, and maybe have an "advanced" option to provide your own keys.

**Comment by IzzySoft** [comment]
@kawaiiDango those API keys are no issues for IzzyOnDroid, which **always** ships the APK you've built & signed. So what about my comment above? Interested?

**Comment by kawaiiDango** [comment]
Yeah, I'm interested. I'll need to make changes to ensure that API keys and other keys are the only things not in the source. Will also prepare the fastlane structure.

**Comment by kawaiiDango** [comment]
@IzzySoft I have a few questions:

Apart from the last.fm and Spotify API keys, I have a pano-embedded-server-ks.p12 keystore and its password not checked in. This is not the apk signing keystore, but is used to provide https to the server (Android no longer allows cleartext traffic by default), used for importing or exporting the settings (a json file) over the local network. The server starts listening on the device's local IPv4 address when you choose "Network" mode in import settings screen and stops when the user navigates away from that screen. This was initially implemented for transferring settings from phones to Android TVs, which do not have the SAF file picker, or a built in way to transfer such files, but now works on all platforms.

1. Do I have to check in that keystore and its password to the source?

I will be building the binaries using this Github workflow https://github.com/kawaiiDango/pano-scrobbler/blob/main/.github/workflows/releases.yml

2. Can you temporarily check for the reproducible build diffs and other things required for your repo, from the artifact produced by that workflow instead of Github releases, before the final release? I'd prefer to not push updates to users for test builds.

===

BTW, I have added the fastlane files and the current build instructions are here https://github.com/kawaiiDango/pano-scrobbler/blob/main/instructions.md Let me know what's missing.

**Comment by Kladki** [comment]
> OK, sorry, but there's a show stopper. Quote:
> 
> > Create a Firebase project for Crashlytics and add the google-services.json …
> 
> Nope. That makes the app ineligible for inclusion, sorry – as it would mean at least 3 non-free/proprietary components: Crashlytics, Firebase, GMS.

But in the very next sentence, it says:

> This is not required for building the releaseGithub (FOSS) variant.

Which is the one you're trying to reproduce anyways, right?

**Comment by IzzySoft** [comment]
> I don't mind putting that keystore and its password in the source. This is for a short-lived https server that only listens on the device's local ipv4 address, so it is "usually" not accessible to the outside world.

To not trigger any "context unaware" security scanner, both could be e.g. base64 encoded and given a less suspicious name, then extracted at build time (maybe even using a gradle task, idk, just thinking aloud here). Or put a note somewhere, explaining why it's no risk; if it's "local only", I agree: it's not worse than an unencrypted session 😉

> We agreed on not checking in the last.fm and Spotify API keys. But you need the complete buildable source for reproducible builds. How do I send you those keys (or rather the file Tokens.kt which contains those keys)?

Having those details to start with, would indeed make things easier for us (otherwise, we had to build with dummies, then diff the resulting APKs – which would then say "eh, diff here: you have `dummy`, they have `real_token`, so we had them then). If you're fine with it, you can send them to me by mail (even PGP encrypted). My mail address can be derived from my account name here, when you hover over the avatar: the domain is the bold one also shown at my comments, with a dot DE appended – and before the AT comes what the hover shows up next to it 😉 

> Firebase

Yes, thanks, got that. Wasn't reading to the end, stopped right at the trigger terms, apologies again!

> Also this

Can only be done once we have all the details together. It's hard to tell what "other" differences mean or not. If I try with dummy tokens, that might also shift addresses – so we might see differences which would simply disappear once the correct tokens are in. I can try as soon as we have that SSL part and the other tokens in place, OK? All I need for that then is an APK and the commit it was built from. I'd then build from the same – and ideally, would end up with a byte-identical APK.

**Comment by IzzySoft** [comment]
Oh, sure, can do!

Fastlane looks excellent, thanks! And the library scanner, as much as it tried, finds nothing to complain. So I'd say, we just wait for the RB, and we're ready to go! Only remaining question would be whether we need to raise the `NonFreeNet` anti-feature – or have a good reason not to. Are any of the supported services non-libre? Are some of them libre? And, if yes to both, are the non-libre ones enabled by default, or not? If there are no non-libre services involved, or those involved are disabled by default as libre ones are available, we would not need the anti-feature.

**Comment by kawaiiDango** [comment]
New release is out.

I ran `rblog build com.arn.scrobble:415`
and got Reproducible: True

I made some changes regarding NonFreeNet.

It no longer supplements data from last.fm by default when the user has not chosen to log in to last.fm, or if the currently selected account is not last.fm, in case they did log in to last.fm in addition to other (libre) scrobbling services. In the login screen, last.fm is no longer the primary button. There isn't a primary button anymore, just a dropdown, listing all the services.

Spotify API is also turned off by default for fresh installations. The app shows a notice, both for upgrades and fresh installations, asking users whether they want to enable/disable loading artist images from Spotify.

**Comment by IzzySoft** [comment]
Confirmed the RB – and also the listing 🥳 Sneak preview from our staging server:

<img width="927" height="861" alt="Image" src="https://github.com/user-attachments/assets/d35faf7d-bef0-4929-b29d-2c31c4419b0b" />

> I made some changes regarding NonFreeNet.

Oh, missed that when setting it up – so no more non-free network access "by default", only after explicit opt-in? Then let me remove the AF again, before the app goes live… done, ignore that part from the screenshot then.

> he app shows a notice, both for upgrades and fresh installations, asking users whether they want to enable/disable loading artist images from Spotify.

Fair enough, so the NonFreeNet warning is not needed – you warn them yourself 😃

OK then, go ahead to our [Badges & Shields](https://izzyondroid.org/about/resources/badges/) page, Pano Scrobbler will go live at `https://apt.izzysoft.de/packages/com.arn.scrobble` in about 2 hours from now. Welcome aboard IzzyOnDroid 😃

PS: your PlayStore listing also has a featureGraphic, which is not available in your Fastlane tree here. You might wish to add that 😉

**Comment by kawaiiDango** [comment]
Oh I didn't notice the featureGraphic being already up at IzzyOnDroid. I don't really care if it is there.
