### ISSUE TITLE
App fails to build because of unresolved reference "song_format_string"

### ISSUE THREAD

**Issue by gennyble** [kawaiiDango/pScrobbler#219]
I'm trying to build pScrobbler and I'm getting some errors. It seems like these are searching for strings that should be in `strings.xml` but were moved to `strings-np.xml` and `strings-sz.xml` in this commit 3c826eed333d720090ed49b80655dbdbc91c7c03, but then removed and the files .gitignored in the very next commit, 4843c8597e1fbb6c4cef0bc10d4c1640eb80b0ee. 

Could you provide these strings in the build instructions or unignore the files?

```
e: pScrobbler/app/src/main/java/com/arn/scrobble/NLService.kt: (289, 35): Unresolved reference: song_format_string
e: pScrobbler/app/src/main/java/com/arn/scrobble/NLService.kt: (298, 35): Unresolved reference: auto_shazam_now_playing
```

**Comment by kawaiiDango** [comment]
They were obtained by decompiling the Android system intelligence and Shazam apks respectively and extracted with a script like https://github.com/gitanuj/nowplayinghistory/blob/master/script.py

I don't think it is safe to put those files on GitHub.

**Comment by Bujiraso** [comment]
hey @kawaiiDango , I also can't build because of this.

Could you elaborate on the safety impacts of keeping the string in the repository?

A few thoughts I had:
* For user stability, it's not user visible, so they'll be okay.
* For developer stability, it already crashes the build and makes the project flaky to reproduce on other hosts.
* For legal, it does not in any way look like these strings are copyrightable.
* For security, it does not look like these contain malware.

I would love to understand where I missed an angle :pray:

**Comment by kawaiiDango** [comment]
> For legal, it does not in any way look like these strings are copyrightable.

I have my doubts with this point, that's why I have removed them.

**Comment by Bujiraso** [comment]
Thanks for the quick reply, @kawaiiDango 

While we may disagree that such a string can be legally protected -- no matter -- in that case, we should simply get the instructions.md fixed up. It was a great help to me other than this one matter.

Correspondingly, I've opened an enhancement: #396
