### ISSUE TITLE
Compatibility with other scrobbling services

### ISSUE THREAD

**Issue by VoidNoire** [kawaiiDango/pScrobbler#3]
It'd be nice if there was support for other services such as libre.fm, listenbrainz, gnufm.

**Comment by kawaiiDango** [comment]
Added scrobble only (no love, no viewing) support for libre.fm, listenbrainz. Couldn't get gnufm server to work for testing, not sure if anyone even uses it

**Comment by VoidNoire** [comment]
Hi thanks for adding support for libre.fm and listenbrainz. I've updated Pano Scrobbler to Version 1.12 - 14.Sep.18 but I'm still unable to authenticate the app to use the libre.fm or listenbrainz services. Upon starting the app, I'm presented with the "Almost there..." page with the options to "Grant notification access" (which I've done),  "Authenticate with last.FM" (which I don't want to do as I don't use last.fm) and the "Choose Apps to scrobble" (which I've also done). How do I authenticate it to scrobble to libre.fm and listenbrainz?

**Comment by kawaiiDango** [comment]
A lastfm login is still needed for the UI. I'm using many lastfm specific APIs which are completely absent on listenbrainz. After the initial login, you can login to other services from settings and maybe disable original lastfm scrobbling

**Comment by VoidNoire** [comment]
I see, thanks for the explanation. I've now been able to authenticate the app to use the libre.fm service. Unfortunately, I'm encountering a new issue. The app crashes whenever I click either of the ListenBrainz options.

**Comment by kawaiiDango** [comment]
That's weird, doesn't happen here. Send a bug report from the app menu, after this happens

**Comment by VoidNoire** [comment]
I've sent it, hopefully you've got it. The bug reporter wouldn't work before as it doesn't recognize Tutanota as an email client, so I've had to install FairEmail.

**Comment by kawaiiDango** [comment]
Its failing with a resource not found exception. 
Check if this build works. https://www.dropbox.com/s/21qosvm79i1tmll/pScrobbler-release.apk?dl=0
If it doesn't, try disabling xposed once.

**Comment by VoidNoire** [comment]
Awesome that version works.

**Comment by KharmaScribbles** [comment]
Can we adjust the configuration so that it follows Listenbrainz API rules for "Listens"? [Listens = Scrobbles] 

> "Listens should be submitted for tracks when the user has listened to half the track **or 4 minutes of the track**, whichever is lower. If the user hasn’t listened to 4 minutes or half the track, it doesn’t fully count as a listen and should not be submitted."

`via ListenBrainz API Docs`
[https://listenbrainz.readthedocs.io/en/latest/dev/api.html#api-calls](https://listenbrainz.readthedocs.io/en/latest/dev/api.html#api-calls)

Really all you'd need to do is change the seconds slider to be longer, as right now mine only accepts 120 seconds.  [  _I realise that most songs reach half way long before the 4 minute mark, but it would still be nice for the odd longer playing track - and to allow us that are playing with listenbrainz to "listen by the rules" if we are in to that sort of thing >__>_  ]  
Also, I prefer to submit my scrobbles based on percent of track played instead of time, so the ability to set a very high play time to ensure I only scrobble by percent played is a feature I need.  I was a little upset that I was so limited by the 90 second delay, as I like to scrobble at around 55%. (Even an option to only scrobble by % played or only playtime would be nice to..)

**Comment by kawaiiDango** [comment]
I never actually read those. Made that as default and increased the delay secs range. I dont want to make scrobble by percent as the default, as some players report the wrong duration, and then some report it in seconds, and some in millis.
