### ISSUE TITLE
artist name with ";" ignored

### ISSUE THREAD

**Issue by rekhubs** [kawaiiDango/pScrobbler#4]
hi, first of all, thanks for your amazing app!!
i'm using this music app Xiami, where multiple artists for a song is displayed as "Adele; Utada Hikaru; Drake".
i guess it's the ";" causing the app to ignore the tracks. would you please confirm and do 

something like:
artists: string[] = artist.replace(/ *; */, ';').split(';')

cheers!

**Comment by cptchi** [comment]
I use Xiami too, and  it scrobbled just fine.
tbh I wish there was a way for it to ignore or prioritize the first artist in featuring cases. Xiami has feats as "Artist 1; Artist 2" and NetEase Cloud Music has it as "Artist 1/Artist 2" and scrobbling like that will create a new artist tag because Last.fm can't handle more than 1 artist in the field. :/

**Comment by kawaiiDango** [comment]
added ; as a seperator. The first artist will be considered.

**Comment by KraXen72** [comment]
could you please add ', ' as a configurable separator? it's how [auxio](https://github.com/OxygenCobalt/Auxio) shows properly tagged multiple artist entries, such as 

Cemetery Drive, kyaru

since some artists might have ', ' in their name, this should be configurable imo. thanks.

**Comment by kawaiiDango** [comment]
> could you please add ', ' as a configurable separator? it's how [auxio](https://github.com/OxygenCobalt/Auxio) shows properly tagged multiple artist entries, such as 
> 
> Cemetery Drive, kyaru
> 
> since some artists might have ', ' in their name, this should be configurable imo. thanks.

You can do that with regex edits.
